name: 3. Publish Coverage Report
env:
  DOTNET_VERSION: '8.0'
on: push

jobs:
  test-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configurando la versión de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies & Run tests with coverage
      run: |
        cd Bank
        dotnet restore
        dotnet test --collect:"XPlat Code Coverage"
    
    - name: Install ReportGenerator
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        dotnet tool install -g dotnet-stryker
    
    - name: Generate coverage Report
      run: |
        cd Bank
        reportgenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:"HTML"
    
    - name: Deploy coverage report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Bank/Cobertura
        destination_dir: docs/Cobertura
        keep_files: true 