name: Publish Coverage Report

on:
  push:
    branches: [ main ]
    paths:
      - 'Bank/**/*.cs'
      - 'Bank/**/*.csproj'
      - '.github/workflows/publish_cov_report.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Bank/Bank.sln
    
    - name: Build
      run: dotnet build Bank/Bank.sln --configuration Release --no-restore
    
    - name: Test with Coverage
      run: dotnet test Bank/Bank.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate Coverage Report
      run: reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage/report -reporttypes:Html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage/report
        destination_dir: coverage
