name: Publish Mutation Report

on:
  push:
    branches: [ main ]
    paths:
      - 'Bank/**/*.cs'
      - 'Bank/**/*.csproj'
      - '.github/workflows/publish_mut_report.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Bank/Bank.sln
    
    - name: Build
      run: dotnet build Bank/Bank.sln --configuration Release --no-restore
    
    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker
    
    - name: Run Mutation Testing
      run: |
        cd Bank/Bank.Domain.Tests
        dotnet stryker
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bank/Bank.Domain.Tests/StrykerOutput
        destination_dir: mutation
